######################################################################
# Automatically generated by qmake (3.0) qui jan 12 02:56:06 2017
######################################################################

TEMPLATE = app
TARGET = "8-CHIP Emulator"
INCLUDEPATH += .

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

# Input
HEADERS += chip8Core.h mainwindow.h
FORMS += mainwindow.ui
SOURCES += chip8Core.cpp main.cpp mainwindow.cpp
